---
- name: Get NGINX Plus version
  set_fact:
    key_value: "" # appeasing the linter
    nginx_plus_version: "{{ ansible_facts.packages['nginx-plus'] | map(attribute='version') | list | first | regex_search('^(\\d{1,3})') }}"
  when: "'nginx-plus' in ansible_facts.packages"

- name: Fail if existing NGINX+ version preconditions fail
  assert:
    that:
      - nginx_plus_version | int >= 19
    fail_msg: >
      "'nginx_plus_version' release version must be a minimum of 19 for App Protect.
      Actual: {{ (nginx_plus_version is defined) | ternary(nginx_plus_version, 'NONE') }}"
    success_msg: "'nginx_plus_version' is {{ (nginx_plus_version is defined) | ternary(nginx_plus_version, 'NONE') }}"
    quiet: true
  when: nginx_plus_version is defined

- name: "(Install: Linux) Create override for NGINX Plus service"
  file:
    path: /etc/systemd/system/nginx.service.d
    state: directory
    mode: '0755'
  when: nginx_timeout is defined

- name: "(Install: Linux) Increase timeout for NGINX Plus Service"
  template:
    src: nginx.service.override.conf.j2
    dest: /etc/systemd/system/nginx.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  when: nginx_timeout is defined

- name: "(Install: Linux) Install NGINX Plus"
  import_tasks: install-app-protect-linux.yml
