---
- import_tasks: setup-debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: setup-redhat.yml
  when: ansible_os_family == "RedHat"

- name: "(Install: Linux) Install NGINX App Protect"
  package:
    name: "app-protect{{ nginx_version | default('') }}"
    state: "{{ app_protect_state }}"
  notify: "(Handler: All OSs) Restart NGINX"
