---
- name: "Setup NGINX App Protect Repositories"
  block:

    - import_tasks: setup-debian-repos.yml
      when: ansible_os_family == "Debian"

    - import_tasks: setup-redhat-repos.yml
      when: ansible_os_family == "RedHat"

  when: app_protect_state != "absent"

- name: "(Install: Linux) Install NGINX App Protect"
  package:
    name: "app-protect{{ app_protect_version | default('') }}"
    state: "{{ app_protect_state }}"
  notify: "(Handler: All OSs) Restart NGINX"
