---
- name: set supported_os when platform and version are in supported platforms dictionary
  set_fact:
    key_value: "" # appeasing the linter
    supported_os: true
  loop: "{{ query('dict', app_protect_linux_families) }}"
  when: ansible_os_family in item.key and ansible_distribution_version | float in item.value

- name: set supported_os to false if fact not defined
  set_fact:
    key_value: "" # appeasing the linter
    supported_os: false
  when: supported_os is not defined

- name: debug supported os
  debug:
    msg: "supported_os {{ supported_os }}"
    verbosity: 2

- name: Abort if the OS/version combination is not supported
  fail:
    msg: "NGINX App Protect is not supported on os family {{ ansible_os_family }} version {{ ansible_distribution_version }}"
  when: not supported_os

- name: "(Install: Linux) Install NGINX Plus App Protect"
  include_tasks: install-app-protect-linux.yml
  when: supported_os and app_protect_install

- name: "Configure NGINX Plus App Protect"
  include_tasks: configure-app-protect.yml
  when: supported_os and app_protect_configure
