---
- name: "(Setup: All OSs Besides Alpine Linux) Setup NGINX App Protect License"
  block:

    - name: "(Setup: All OSs Besides Alpine Linux) Create SSL Directory"
      file:
        path: /etc/ssl/nginx
        state: directory

    - name: "(Setup: All OSs Besides Alpine Linux) Copy NGINX App Protect Certificate and License Key"
      copy:
        src: "{{ item }}"
        dest: /etc/ssl/nginx
        decrypt: true
      with_items:
        - "{{ nginx_license.certificate }}"
        - "{{ nginx_license.key }}"

  when: ansible_distribution != "Alpine"