---
- name: "(Install: APT OSs) Set Default APT NGINX App Protect Signing Key URL"
  set_fact:
    key_value: "" # appeasing the linter
    default_keysite: "http://nginx.org/keys/nginx_signing.key"

- name: "(Install: APT OSs) Set APT NGINX App Protect Signing Key URL"
  set_fact:
    key_value: "" # appeasing the linter
    keysite: "{{ app_protect_signing_key | default(default_keysite) }}"

- name: "(Install: APT OSs) Add APT NGINX App Protect Signing Key"
  apt_key:
    url: "{{ keysite }}"
