---
- name: "(Install: RPM OSs) Set Default RPM NGINX App Protect Signing Key"
  set_fact:
    key_value: "" # appeasing the linter
    default_keysite: "http://nginx.org/keys/nginx_signing.key"

- name: "(Install: RPM OSs) Set RPM NGINX App Protect Signing Key URL"
  set_fact:
    key_value: "" # appeasing the linter
    keysite: "{{ app_protect_signing_key | default(default_keysite) }}"

- name: "(Install: RPM OSs) Add RPM NGINX App Protect Signing Key"
  rpm_key:
    key: "{{ keysite }}"
