---
- name: "(Install: RPM OSs) Set Default RPM NGINX Signing Key"
  set_fact:
    key_value: "" # appeasing the linter
    nginx_keysite: "{{ nginx_signing_key | default('https://cs.nginx.com/static/keys/nginx_signing.key') }}"

- name: "(Install: RPM OSs) Set Default RPM NGINX App Protect Signing Key"
  set_fact:
    key_value: "" # appeasing the linter
    app_protect_keysite: "{{ app_protect_signing_key | default('https://cs.nginx.com/static/keys/app-protect.key') }}"

- name: "(Install: RPM OSs) Add RPM NGINX Signing Key"
  rpm_key:
    key: "{{ nginx_keysite }}"

- name: "(Install: RPM OSs) Add RPM NGINX App Protect Signing Key"
  rpm_key:
    key: "{{ app_protect_keysite }}"
