---
# handlers file for ansible-role-nginx-app-protect
- name: "(Handler: All OSs) Run NGINX"
  block:

    - name: "(Handler: All OSs) Start NGINX"
      service:
        name: nginx
        state: started
        enabled: true

    - name: "(Handler: All OSs) Restart NGINX"
      service:
        name: nginx
        state: restarted

  when:
    - nginx_start | bool
    - not ansible_check_mode
