---
# handlers file for ansible-role-nginx-app-protect
- name: "(Handler: All OSs) Run NGINX"
  block:

    - name: "(Handler: All OSs) Start NGINX"
      service:
        name: nginx
        state: started
        enabled: true
      notify: "(Handler: All OSs) Check NGINX"

    - name: "(Handler: All OSs) Restart NGINX"
      service:
        name: nginx
        state: restarted
      changed_when: false

  when:
    - nginx_start | bool
    - not ansible_check_mode

- name: "(Handler: All OSs) Check NGINX"
  command: "nginx -t"
  changed_when: false
